title: janstuemmel.de
description: Personal homepage of Jan Stümmel. Programmer. GO, PHP, Javascript, Node.
keywords: jan stümmel, programming, go, php, node, javascript, js, berlin, freising, germany
url: "https://janstuemmel.de"
mail: info@janstuemmel.de
baseurl: ""

colors: 
  - "#16a085"
  - "#8e44ad"
  - "#2980b9"
  - "#d35400"
  - "#f39c12"
  - "#6c5ce7"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"